/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import org.xtext.example.entity.ui.internal.EntityActivator;

public class EntityUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return EntityActivator.getInstance().getInjector("org.xtext.example.Entity");
	}

}
