/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example;

import org.xtext.example.EntityStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class EntityStandaloneSetup extends EntityStandaloneSetupGenerated {
  public static void doSetup() {
    EntityStandaloneSetup _entityStandaloneSetup = new EntityStandaloneSetup();
    _entityStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
