/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.entity;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.entity.EntityFactory
 * @model kind="package"
 * @generated
 */
public interface EntityPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "entity";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/Entity";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "entity";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  EntityPackage eINSTANCE = org.xtext.example.entity.impl.EntityPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.entity.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.entity.impl.ModelImpl
   * @see org.xtext.example.entity.impl.EntityPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.entity.impl.expressionImpl <em>expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.entity.impl.expressionImpl
   * @see org.xtext.example.entity.impl.EntityPackageImpl#getexpression()
   * @generated
   */
  int EXPRESSION = 1;

  /**
   * The feature id for the '<em><b>Expressao un</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__EXPRESSAO_UN = 0;

  /**
   * The feature id for the '<em><b>Operador</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__OPERADOR = 1;

  /**
   * The feature id for the '<em><b>Expressao</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__EXPRESSAO = 2;

  /**
   * The number of structural features of the '<em>expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.entity.impl.expression_unityImpl <em>expression unity</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.entity.impl.expression_unityImpl
   * @see org.xtext.example.entity.impl.EntityPackageImpl#getexpression_unity()
   * @generated
   */
  int EXPRESSION_UNITY = 2;

  /**
   * The feature id for the '<em><b>Menos</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_UNITY__MENOS = 0;

  /**
   * The feature id for the '<em><b>Expressao un</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_UNITY__EXPRESSAO_UN = 1;

  /**
   * The feature id for the '<em><b>Abre paren</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_UNITY__ABRE_PAREN = 2;

  /**
   * The feature id for the '<em><b>Expressao</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_UNITY__EXPRESSAO = 3;

  /**
   * The feature id for the '<em><b>Fecha paren</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_UNITY__FECHA_PAREN = 4;

  /**
   * The feature id for the '<em><b>Valor</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_UNITY__VALOR = 5;

  /**
   * The number of structural features of the '<em>expression unity</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_UNITY_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link org.xtext.example.entity.impl.operatorImpl <em>operator</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.entity.impl.operatorImpl
   * @see org.xtext.example.entity.impl.EntityPackageImpl#getoperator()
   * @generated
   */
  int OPERATOR = 3;

  /**
   * The feature id for the '<em><b>Mais</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATOR__MAIS = 0;

  /**
   * The feature id for the '<em><b>Menos</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATOR__MENOS = 1;

  /**
   * The feature id for the '<em><b>Mult</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATOR__MULT = 2;

  /**
   * The feature id for the '<em><b>Div</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATOR__DIV = 3;

  /**
   * The number of structural features of the '<em>operator</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATOR_FEATURE_COUNT = 4;


  /**
   * Returns the meta object for class '{@link org.xtext.example.entity.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.entity.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.entity.Model#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.xtext.example.entity.Model#getElements()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Elements();

  /**
   * Returns the meta object for class '{@link org.xtext.example.entity.expression <em>expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>expression</em>'.
   * @see org.xtext.example.entity.expression
   * @generated
   */
  EClass getexpression();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.entity.expression#getExpressao_un <em>Expressao un</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expressao un</em>'.
   * @see org.xtext.example.entity.expression#getExpressao_un()
   * @see #getexpression()
   * @generated
   */
  EReference getexpression_Expressao_un();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.entity.expression#getOperador <em>Operador</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Operador</em>'.
   * @see org.xtext.example.entity.expression#getOperador()
   * @see #getexpression()
   * @generated
   */
  EReference getexpression_Operador();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.entity.expression#getExpressao <em>Expressao</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expressao</em>'.
   * @see org.xtext.example.entity.expression#getExpressao()
   * @see #getexpression()
   * @generated
   */
  EReference getexpression_Expressao();

  /**
   * Returns the meta object for class '{@link org.xtext.example.entity.expression_unity <em>expression unity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>expression unity</em>'.
   * @see org.xtext.example.entity.expression_unity
   * @generated
   */
  EClass getexpression_unity();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.entity.expression_unity#getMenos <em>Menos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Menos</em>'.
   * @see org.xtext.example.entity.expression_unity#getMenos()
   * @see #getexpression_unity()
   * @generated
   */
  EAttribute getexpression_unity_Menos();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.entity.expression_unity#getExpressao_un <em>Expressao un</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expressao un</em>'.
   * @see org.xtext.example.entity.expression_unity#getExpressao_un()
   * @see #getexpression_unity()
   * @generated
   */
  EReference getexpression_unity_Expressao_un();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.entity.expression_unity#getAbre_paren <em>Abre paren</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Abre paren</em>'.
   * @see org.xtext.example.entity.expression_unity#getAbre_paren()
   * @see #getexpression_unity()
   * @generated
   */
  EAttribute getexpression_unity_Abre_paren();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.entity.expression_unity#getExpressao <em>Expressao</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expressao</em>'.
   * @see org.xtext.example.entity.expression_unity#getExpressao()
   * @see #getexpression_unity()
   * @generated
   */
  EReference getexpression_unity_Expressao();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.entity.expression_unity#getFecha_paren <em>Fecha paren</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Fecha paren</em>'.
   * @see org.xtext.example.entity.expression_unity#getFecha_paren()
   * @see #getexpression_unity()
   * @generated
   */
  EAttribute getexpression_unity_Fecha_paren();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.entity.expression_unity#getValor <em>Valor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Valor</em>'.
   * @see org.xtext.example.entity.expression_unity#getValor()
   * @see #getexpression_unity()
   * @generated
   */
  EAttribute getexpression_unity_Valor();

  /**
   * Returns the meta object for class '{@link org.xtext.example.entity.operator <em>operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>operator</em>'.
   * @see org.xtext.example.entity.operator
   * @generated
   */
  EClass getoperator();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.entity.operator#getMais <em>Mais</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Mais</em>'.
   * @see org.xtext.example.entity.operator#getMais()
   * @see #getoperator()
   * @generated
   */
  EAttribute getoperator_Mais();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.entity.operator#getMenos <em>Menos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Menos</em>'.
   * @see org.xtext.example.entity.operator#getMenos()
   * @see #getoperator()
   * @generated
   */
  EAttribute getoperator_Menos();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.entity.operator#getMult <em>Mult</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Mult</em>'.
   * @see org.xtext.example.entity.operator#getMult()
   * @see #getoperator()
   * @generated
   */
  EAttribute getoperator_Mult();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.entity.operator#getDiv <em>Div</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Div</em>'.
   * @see org.xtext.example.entity.operator#getDiv()
   * @see #getoperator()
   * @generated
   */
  EAttribute getoperator_Div();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  EntityFactory getEntityFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.entity.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.entity.impl.ModelImpl
     * @see org.xtext.example.entity.impl.EntityPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ELEMENTS = eINSTANCE.getModel_Elements();

    /**
     * The meta object literal for the '{@link org.xtext.example.entity.impl.expressionImpl <em>expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.entity.impl.expressionImpl
     * @see org.xtext.example.entity.impl.EntityPackageImpl#getexpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getexpression();

    /**
     * The meta object literal for the '<em><b>Expressao un</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__EXPRESSAO_UN = eINSTANCE.getexpression_Expressao_un();

    /**
     * The meta object literal for the '<em><b>Operador</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__OPERADOR = eINSTANCE.getexpression_Operador();

    /**
     * The meta object literal for the '<em><b>Expressao</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__EXPRESSAO = eINSTANCE.getexpression_Expressao();

    /**
     * The meta object literal for the '{@link org.xtext.example.entity.impl.expression_unityImpl <em>expression unity</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.entity.impl.expression_unityImpl
     * @see org.xtext.example.entity.impl.EntityPackageImpl#getexpression_unity()
     * @generated
     */
    EClass EXPRESSION_UNITY = eINSTANCE.getexpression_unity();

    /**
     * The meta object literal for the '<em><b>Menos</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESSION_UNITY__MENOS = eINSTANCE.getexpression_unity_Menos();

    /**
     * The meta object literal for the '<em><b>Expressao un</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION_UNITY__EXPRESSAO_UN = eINSTANCE.getexpression_unity_Expressao_un();

    /**
     * The meta object literal for the '<em><b>Abre paren</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESSION_UNITY__ABRE_PAREN = eINSTANCE.getexpression_unity_Abre_paren();

    /**
     * The meta object literal for the '<em><b>Expressao</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION_UNITY__EXPRESSAO = eINSTANCE.getexpression_unity_Expressao();

    /**
     * The meta object literal for the '<em><b>Fecha paren</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESSION_UNITY__FECHA_PAREN = eINSTANCE.getexpression_unity_Fecha_paren();

    /**
     * The meta object literal for the '<em><b>Valor</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESSION_UNITY__VALOR = eINSTANCE.getexpression_unity_Valor();

    /**
     * The meta object literal for the '{@link org.xtext.example.entity.impl.operatorImpl <em>operator</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.entity.impl.operatorImpl
     * @see org.xtext.example.entity.impl.EntityPackageImpl#getoperator()
     * @generated
     */
    EClass OPERATOR = eINSTANCE.getoperator();

    /**
     * The meta object literal for the '<em><b>Mais</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPERATOR__MAIS = eINSTANCE.getoperator_Mais();

    /**
     * The meta object literal for the '<em><b>Menos</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPERATOR__MENOS = eINSTANCE.getoperator_Menos();

    /**
     * The meta object literal for the '<em><b>Mult</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPERATOR__MULT = eINSTANCE.getoperator_Mult();

    /**
     * The meta object literal for the '<em><b>Div</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPERATOR__DIV = eINSTANCE.getoperator_Div();

  }

} //EntityPackage
