/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.entity;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.example.entity.expression#getExpressao_un <em>Expressao un</em>}</li>
 *   <li>{@link org.xtext.example.entity.expression#getOperador <em>Operador</em>}</li>
 *   <li>{@link org.xtext.example.entity.expression#getExpressao <em>Expressao</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.example.entity.EntityPackage#getexpression()
 * @model
 * @generated
 */
public interface expression extends EObject
{
  /**
   * Returns the value of the '<em><b>Expressao un</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expressao un</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expressao un</em>' containment reference.
   * @see #setExpressao_un(expression_unity)
   * @see org.xtext.example.entity.EntityPackage#getexpression_Expressao_un()
   * @model containment="true"
   * @generated
   */
  expression_unity getExpressao_un();

  /**
   * Sets the value of the '{@link org.xtext.example.entity.expression#getExpressao_un <em>Expressao un</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expressao un</em>' containment reference.
   * @see #getExpressao_un()
   * @generated
   */
  void setExpressao_un(expression_unity value);

  /**
   * Returns the value of the '<em><b>Operador</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Operador</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operador</em>' containment reference.
   * @see #setOperador(operator)
   * @see org.xtext.example.entity.EntityPackage#getexpression_Operador()
   * @model containment="true"
   * @generated
   */
  operator getOperador();

  /**
   * Sets the value of the '{@link org.xtext.example.entity.expression#getOperador <em>Operador</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operador</em>' containment reference.
   * @see #getOperador()
   * @generated
   */
  void setOperador(operator value);

  /**
   * Returns the value of the '<em><b>Expressao</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expressao</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expressao</em>' containment reference.
   * @see #setExpressao(expression)
   * @see org.xtext.example.entity.EntityPackage#getexpression_Expressao()
   * @model containment="true"
   * @generated
   */
  expression getExpressao();

  /**
   * Sets the value of the '{@link org.xtext.example.entity.expression#getExpressao <em>Expressao</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expressao</em>' containment reference.
   * @see #getExpressao()
   * @generated
   */
  void setExpressao(expression value);

} // expression
