/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.entity;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>expression unity</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.example.entity.expression_unity#getMenos <em>Menos</em>}</li>
 *   <li>{@link org.xtext.example.entity.expression_unity#getExpressao_un <em>Expressao un</em>}</li>
 *   <li>{@link org.xtext.example.entity.expression_unity#getAbre_paren <em>Abre paren</em>}</li>
 *   <li>{@link org.xtext.example.entity.expression_unity#getExpressao <em>Expressao</em>}</li>
 *   <li>{@link org.xtext.example.entity.expression_unity#getFecha_paren <em>Fecha paren</em>}</li>
 *   <li>{@link org.xtext.example.entity.expression_unity#getValor <em>Valor</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.example.entity.EntityPackage#getexpression_unity()
 * @model
 * @generated
 */
public interface expression_unity extends EObject
{
  /**
   * Returns the value of the '<em><b>Menos</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Menos</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Menos</em>' attribute.
   * @see #setMenos(String)
   * @see org.xtext.example.entity.EntityPackage#getexpression_unity_Menos()
   * @model
   * @generated
   */
  String getMenos();

  /**
   * Sets the value of the '{@link org.xtext.example.entity.expression_unity#getMenos <em>Menos</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Menos</em>' attribute.
   * @see #getMenos()
   * @generated
   */
  void setMenos(String value);

  /**
   * Returns the value of the '<em><b>Expressao un</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expressao un</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expressao un</em>' containment reference.
   * @see #setExpressao_un(expression_unity)
   * @see org.xtext.example.entity.EntityPackage#getexpression_unity_Expressao_un()
   * @model containment="true"
   * @generated
   */
  expression_unity getExpressao_un();

  /**
   * Sets the value of the '{@link org.xtext.example.entity.expression_unity#getExpressao_un <em>Expressao un</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expressao un</em>' containment reference.
   * @see #getExpressao_un()
   * @generated
   */
  void setExpressao_un(expression_unity value);

  /**
   * Returns the value of the '<em><b>Abre paren</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Abre paren</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Abre paren</em>' attribute.
   * @see #setAbre_paren(String)
   * @see org.xtext.example.entity.EntityPackage#getexpression_unity_Abre_paren()
   * @model
   * @generated
   */
  String getAbre_paren();

  /**
   * Sets the value of the '{@link org.xtext.example.entity.expression_unity#getAbre_paren <em>Abre paren</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Abre paren</em>' attribute.
   * @see #getAbre_paren()
   * @generated
   */
  void setAbre_paren(String value);

  /**
   * Returns the value of the '<em><b>Expressao</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expressao</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expressao</em>' containment reference.
   * @see #setExpressao(expression)
   * @see org.xtext.example.entity.EntityPackage#getexpression_unity_Expressao()
   * @model containment="true"
   * @generated
   */
  expression getExpressao();

  /**
   * Sets the value of the '{@link org.xtext.example.entity.expression_unity#getExpressao <em>Expressao</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expressao</em>' containment reference.
   * @see #getExpressao()
   * @generated
   */
  void setExpressao(expression value);

  /**
   * Returns the value of the '<em><b>Fecha paren</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fecha paren</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fecha paren</em>' attribute.
   * @see #setFecha_paren(String)
   * @see org.xtext.example.entity.EntityPackage#getexpression_unity_Fecha_paren()
   * @model
   * @generated
   */
  String getFecha_paren();

  /**
   * Sets the value of the '{@link org.xtext.example.entity.expression_unity#getFecha_paren <em>Fecha paren</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fecha paren</em>' attribute.
   * @see #getFecha_paren()
   * @generated
   */
  void setFecha_paren(String value);

  /**
   * Returns the value of the '<em><b>Valor</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Valor</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Valor</em>' attribute.
   * @see #setValor(int)
   * @see org.xtext.example.entity.EntityPackage#getexpression_unity_Valor()
   * @model
   * @generated
   */
  int getValor();

  /**
   * Sets the value of the '{@link org.xtext.example.entity.expression_unity#getValor <em>Valor</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Valor</em>' attribute.
   * @see #getValor()
   * @generated
   */
  void setValor(int value);

} // expression_unity
