/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.entity;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>operator</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.example.entity.operator#getMais <em>Mais</em>}</li>
 *   <li>{@link org.xtext.example.entity.operator#getMenos <em>Menos</em>}</li>
 *   <li>{@link org.xtext.example.entity.operator#getMult <em>Mult</em>}</li>
 *   <li>{@link org.xtext.example.entity.operator#getDiv <em>Div</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.example.entity.EntityPackage#getoperator()
 * @model
 * @generated
 */
public interface operator extends EObject
{
  /**
   * Returns the value of the '<em><b>Mais</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Mais</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mais</em>' attribute.
   * @see #setMais(String)
   * @see org.xtext.example.entity.EntityPackage#getoperator_Mais()
   * @model
   * @generated
   */
  String getMais();

  /**
   * Sets the value of the '{@link org.xtext.example.entity.operator#getMais <em>Mais</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mais</em>' attribute.
   * @see #getMais()
   * @generated
   */
  void setMais(String value);

  /**
   * Returns the value of the '<em><b>Menos</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Menos</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Menos</em>' attribute.
   * @see #setMenos(String)
   * @see org.xtext.example.entity.EntityPackage#getoperator_Menos()
   * @model
   * @generated
   */
  String getMenos();

  /**
   * Sets the value of the '{@link org.xtext.example.entity.operator#getMenos <em>Menos</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Menos</em>' attribute.
   * @see #getMenos()
   * @generated
   */
  void setMenos(String value);

  /**
   * Returns the value of the '<em><b>Mult</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Mult</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mult</em>' attribute.
   * @see #setMult(String)
   * @see org.xtext.example.entity.EntityPackage#getoperator_Mult()
   * @model
   * @generated
   */
  String getMult();

  /**
   * Sets the value of the '{@link org.xtext.example.entity.operator#getMult <em>Mult</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mult</em>' attribute.
   * @see #getMult()
   * @generated
   */
  void setMult(String value);

  /**
   * Returns the value of the '<em><b>Div</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Div</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Div</em>' attribute.
   * @see #setDiv(String)
   * @see org.xtext.example.entity.EntityPackage#getoperator_Div()
   * @model
   * @generated
   */
  String getDiv();

  /**
   * Sets the value of the '{@link org.xtext.example.entity.operator#getDiv <em>Div</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Div</em>' attribute.
   * @see #getDiv()
   * @generated
   */
  void setDiv(String value);

} // operator
